export default {
    customerList: [
        {
            currency: 0,
            selectFavorites: ['5f452e737d7bc77ebf3defd1'],
            channels: [
                {
                    categories: ['5ecc2f749bcdc97f0c028743', '5ecc2f749bcdc97f0c028742', '5f2052fa537bdb617a558856'],
                    _id: '5f452fa67d7bc77ebf3defd4',
                    code: '3',
                    name: '意大利1',
                    currency: 2,
                    createTime: '2020-08-25T15:35:02.078Z',
                    updateTime: '2021-01-12T21:46:50.292Z',
                },
            ],
            goods: [],
            _id: '5f4e72bf7d7bc77ebf3df009',
            account: 'ZS',
            password: '12345',
            role: 3,
            name: '张三',
            createTime: '2020-09-01T16:11:43.831Z',
            updateTime: '2020-09-01T16:37:56.314Z',
            id: '5f4e72bf7d7bc77ebf3df009',
        },
        {
            currency: 0,
            selectFavorites: [],
            channels: [
                {
                    categories: ['5f2820a757ca0e7bac09cfce', '5f2820a757ca0e7bac09cfcd'],
                    _id: '5f968c7f646d3d4670cb32e4',
                    code: '5',
                    name: 'California',
                    currency: 2,
                    createTime: '2020-10-26T08:44:47.629Z',
                    updateTime: '2020-10-26T08:49:24.482Z',
                },
            ],
            goods: [],
            _id: '5f968cb0646d3d4670cb32e5',
            account: 'MAITE',
            password: '12345',
            role: 3,
            name: 'MAITE',
            createTime: '2020-10-26T08:45:36.385Z',
            updateTime: '2020-10-26T08:45:36.385Z',
            id: '5f968cb0646d3d4670cb32e5',
        },
    ],
    currentCustomer: {
        _id: '5f4e72bf7d7bc77ebf3df009',
        name: '张三',
    },
    currentCustomerEmpowerInfo: [
        {
            name: 'DIY 搭配',
            key: 'diy',
            goodsInfo: [
                {
                    _id: '5ecc2f749bcdc97f0c028741',
                    name: 'YI',
                    aliasName: '意大利泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    empowered: false,
                },
                {
                    _id: '5ecc2edb9bcdc97f0c02872b',
                    name: 'LI',
                    aliasName: '葡萄牙泳装',
                    channel: 'B',
                    channelInfo: '全部显示',
                    empowered: true,
                },
                {
                    _id: '5ecc2f4f9bcdc97f0c02873e',
                    name: 'SEVILLA',
                    aliasName: '塞维利亚泳装',
                    channel: 'B',
                    channelInfo: '全部显示',
                    empowered: false,
                },
            ],
        },
        {
            key: 'capsule',
            name: '胶囊产品系列',
            goodsInfo: [
                {
                    _id: '5f205258537bdb617a558848',
                    name: 'DO',
                    aliasName: '马拉加泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    empowered: true,
                },
                {
                    _id: '5f3ec29297926f3800d96293',
                    name: 'YI-2',
                    aliasName: '德国泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    empowered: false,
                },
                {
                    _id: '5f2820a757ca0e7bac09cfcc',
                    name: 'JZ',
                    aliasName: '加州泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    empowered: false,
                },
            ],
        },
        {
            key: 'shop',
            name: '现货购买',
            goodsInfo: [
                {
                    _id: '5f205258537bss617a558848',
                    name: 'DO',
                    aliasName: '马拉加泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    empowered: true,
                },
                {
                    _id: '5f3ec29297ss6f3800d96293',
                    name: 'YI-2',
                    aliasName: '德国泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    empowered: false,
                },
                {
                    _id: '5f2820a757cadd7bac09cfcc',
                    name: 'JZ',
                    aliasName: '加州泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    empowered: false,
                },
            ],
        },
        {
            key: 'channelEmpowerUserd',
            name: '通道分配器的使用授权',
            empowered: false,
        },
        {
            key: 'innerDataUserd',
            name: '内部数据分析的使用权限',
            empowered: true,
        },
        { key: 'businessUserd', name: '业务管理的使用权限', empowered: true },
    ],
    channelEmpowerInfo: [
        {
            name: 'DIY 搭配',
            key: 'diy',
            goodsInfo: [
                {
                    _id: '5ecc2f749bcdc97f0c028741',
                    name: 'YI',
                    aliasName: '意大利泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    channelEmpowereds: [
                        {
                            channel: 'B',
                            empowered: 1,
                        },
                        {
                            channel: 'C',
                            empowered: 1,
                        },
                    ],
                },
                {
                    _id: '5ecc2edb9bcdc97f0c02872b',
                    name: 'LI',
                    aliasName: '葡萄牙泳装',
                    channel: 'B',
                    channelInfo: '全部显示',
                    channelEmpowereds: { B: 3, C: 1 },
                },
                {
                    _id: '5ecc2f4f9bcdc97f0c02873e',
                    name: 'SEVILLA',
                    aliasName: '塞维利亚泳装',
                    channel: 'B',
                    channelInfo: '全部显示',
                    channelEmpowereds: { B: 3, C: 1 },
                },
            ],
        },
        {
            key: 'capsule',
            name: '胶囊产品系列',
            goodsInfo: [
                {
                    _id: '5f205258537bdb617a558848',
                    name: 'DO',
                    aliasName: '马拉加泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    channelEmpowereds: { B: 3, C: 2 },
                },
                {
                    _id: '5f3ec29297926f3800d96293',
                    name: 'YI-2',
                    aliasName: '德国泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    channelEmpowereds: { B: 2, C: 1 },
                },
                {
                    _id: '5f2820a757ca0e7bac09cfcc',
                    name: 'JZ',
                    aliasName: '加州泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    channelEmpowereds: { B: 1, C: 3 },
                },
            ],
        },
        {
            key: 'shop',
            name: '现货购买',
            goodsInfo: [
                {
                    _id: '5f205258537bss617a558848',
                    name: 'DO',
                    aliasName: '马拉加泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    channelEmpowereds: { B: 3, C: 2 },
                },
                {
                    _id: '5f3ec29297ss6f3800d96293',
                    name: 'YI-2',
                    aliasName: '德国泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    channelEmpowereds: { B: 1, C: 1 },
                },
                {
                    _id: '5f2820a757cadd7bac09cfcc',
                    name: 'JZ',
                    aliasName: '加州泳装',
                    channel: 'B',
                    channelInfo: '专供南部',
                    channelEmpowereds: { B: 1, C: 1 },
                },
            ],
        },
    ],
};
